import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { MacbookScrollDemo } from "@/components/MacBook";
import HeroSection from "@/components/Hero";
import { ShootingStars } from "@/components/ui/shooting-stars";
import { StarsBackground } from "@/components/ui/stars-background";
import '../components/index.css';
import TimeLine from "@/components/TimeLine";
import About from "@/components/About";
import Themes from "@/components/Themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{background:'black'}}>
        <Navbar/>
        <HeroSection />
        {children}
        <TimeLine />        
        <MacbookScrollDemo />
        <About />
        <Themes />


        <ShootingStars />
        <StarsBackground />
        <div className="ellipse1"></div>
        {/* <div className="ellipse2"></div> */}
        <div className="ellipse3"></div>
        <div className="ellipse4"></div>
        {/* <div className="ellipse5"></div> */}
        
      </body>
    </html>
  );
}
